# Autostart
exec-once = waybar
exec-once = brightnessctl s 100%
exec-once = sleep 5; easyeffects -w --service-mode
exec-once = sleep 6; easyeffects -l "Arctis 3"
exec-once = sleep 6; easyeffects -l "Laptop Mic"
