name = "Thread of Time"
author = "heliboss"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2568cc8bcc0aa5ef27d98286fc52cf25a029c54d4e7c5e5e33b99fc66ff6e7b6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"
