name = "Thread of Time"
author = "heliboss"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cfc128e5780966a5bce708d1854422cb513ecf89b305faed01874c3d30d2429"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"
