name = "Thread of Time"
author = "heliboss"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5aadf2863e6d5b531d54781d540317d983bee9b6b3b0ea3b4967ae36dc574b43"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.256"
